SiteName: StreamDingo Documentation
SiteDescription: A high-performance .NET library for event sourcing with hash-based integrity verification
SiteAuthor: Alex Wiese
Host: alexwiese.github.io
BasePath: /StreamDingo
LinkRoot: /StreamDingo

# GitHub integration
GitHub: alexwiese/StreamDingo
GitHubOwner: alexwiese
GitHubName: StreamDingo

# Theme settings
Theme: Samson
EditLink: https://github.com/alexwiese/StreamDingo/edit/main/{Document.Source.Value}

# Search
SearchProvider: Lunr

# Code highlighting
HighlightJS: true

# Disable blog functionality
BlogRssPath: null
BlogAtomPath: null
ArchivePageSize: 0

# Code Analysis for API docs
ProjectFiles:
  - ../src/StreamDingo/StreamDingo.csproj

# Input settings - disable front matter parsing for files without it
ParseYaml: false

# Fix relative links to use .html instead of .md
MarkdownRenderExtensions: true
MarkdownRelativeLinksAsAbsolute: false
ValidateRelativeLinks: true

# Additional theme settings
BootstrapTheme: true

# Configure link resolution
LinkHideExtensions: false