SiteName: StreamDingo Documentation
SiteDescription: A high-performance .NET library for event sourcing with hash-based integrity verification
SiteAuthor: Alex Wiese
Host: alexwiese.github.io
BasePath: /StreamDingo
LinkRoot: /StreamDingo

# GitHub integration
GitHub: alexwiese/StreamDingo
GitHubOwner: alexwiese
GitHubName: StreamDingo

# Input/Output directories
InputFiles: ["**/*.{html,cshtml,md}"]
OutputPath: output

# Rendering settings
ApplyDirectoryMetadata: true
ProcessIncludes: true
ProcessShortcodes: true

# Enable front matter parsing
ParseMarkdownFrontMatter: true